title: Pilosophos' Circle

collections:
    writing:
        output: true
    software:
        output: true
    town:
        output: true
    demos:
        output: true

sass:
    load_paths:
        - assets/css