name: Deploy to Neocities

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build static site
      uses: pilosophos/jekyll-build-action@master
      with:
        config: _config.yml,_config-neocities.yml
    - name: Remove banned file types
      run: find ./site ! -regex '.*/*.\(apng\|asc\|atom\|avif\|bin\|css\|csv\|dae\|eot\|epub\|geojson\|gif\|gltf\|gpg\|htm\|html\|ico\|jpeg\|jpg\|js\|json\|key\|kml\|knowl\|less\|manifest\|map\|markdown\|md\|mf\|mid\|midi\|mtl\|obj\|opml\|osdx\|otf\|pdf\|pgp\|pls\|png\|rdf\|resolveHandle\|rss\|sass\|scss\|svg\|text\|toml\|tsv\|ttf\|txt\|webapp\|webmanifest\|webp\|woff\|woff2\|xcf\|xml\|yaml\|yml\)' -type f -delete
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: './_site'